# This is a boilerplate parameters config generated for pipeline 'gnn_pretraining'
# using Kedro 1.0.0rc1.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/1.0.0rc1/configuration/parameters.html
# Configuration des fenêtres temporelles
# Configuration des fenêtres temporelles
# Configuration pour pré-entraînement GNN
# À ajouter dans: conf/base/parameters.yml

gnn_pretraining:
  
  # Préparation des données
  data_preparation:
    max_nodes_for_training: 50000     # Limite nœuds pour éviter surcharge mémoire
    batch_size: 1000                  # Nœuds par sous-batch
    validation_split: 0.2             # 20% pour validation
    
  # Architecture du modèle  
  model:
    node_dim: 64                      # Dimension embeddings nœuds (selon vos données)
    edge_dim: 64                      # Dimension embeddings arêtes (selon vos données)
    hidden_dim: 128                   # Dimension cachée
    device: "cuda"                    # "cuda" ou "cpu"
    random_seed: 42                   # Pour reproductibilité
    
  # Paramètres d'entraînement
  training:
    learning_rate: 0.001              # Taux d'apprentissage
    num_epochs: 50                    # Nombre max d'époques
    patience: 10                      # Early stopping patience
    min_delta: 0.0001                 # Amélioration minimale
    log_interval: 5                   # Fréquence logs (toutes les N époques)