# Parameters for dissection pipeline

# Input directory
initial_raw_file: "data/initial_raw/benign.pcap"

evil_ip: 10.100.200.66

nb_cluster: 17

feature_list:
  - ip_src
  - ip_dst
  - outer_hdr_creation.ipv4
  - apply_action.forw
  - nfInstances.nfServices.serviceInstanceId
  - nfServices.serviceInstanceId
  - ext_hdr.pdu_ses_con.pdu_type
  - far_id
  - pdr_id
  - apply_action.drop
  - seid
  - method
  - path
  - jwt.scope
  - jwt.sub
  - amfInstanceId
  - nfInstanceId
  - servingNfId
  - target-nf-instance-id
  - nfInstances.nfInstanceId
  - requester-nf-type
  - target-nf-type
  - nf-type
  - ueId
  - supi
  - request.supi
  - supis
  - subscriberIdentifier
  - nfInstances.nfType
  - nfType
  - ausfInstanceId
  - nfServices.ipEndPoints.ipv4Address
  - nfServices.serviceName
  - imsi
  - service-names
  - nfInstances.ipv4Addresses
  - ipv4Addresses
  - f_seid.ipv4
  - ipv4Address
  - ue_ip_addr_ipv4
  - f_teid.ipv4_addr
  - f_teid.teid
  - outer_hdr_creation.teid
  - teid
  - smsfInstanceId
  - cause
  - msg_type
  - http2
  - ip_src
  - ip_dst
  - ip
  - gtp
  - pfcp

input_tensor_dimension: 1024

window_size: 1000
window_shift: 500

split_ratio: 0.80
# split_ratio: 1.0
batch_size: 32

training_params :
  learning_rate: 0.005
  weight_decay: 0.001
  num_epochs: 100
  early_stopping_patience: 15
  log_interval: 10
  batch_size: 32
