# Parameters for dissection pipeline

# Input directory
input_trace_dir: "data/01_raw/pcap_files"

# Processing parameters  
buffer_size: 1000

# Banned features list
banned_features:
  - "versions"
  - "scheme"
  - "ipEndPoints"
  - "apiPrefix"
  - "subscribedUeAmbr"
  - "dnnInfos"
  - "jwt.alg"
  - "jwt.typ"