# Parameters for dissection pipeline

# Input directory
initial_raw_file: "data/initial_raw/benign.pcap"

evil_ip: 10.100.200.66

nb_cluster: 17

# Banned features list
banned_features:
  - "versions"
  - "scheme"
  - "subscribedUeAmbr"
  - "dnnInfos"
  - "jwt.alg"
  - "jwt.typ"
  - "start_time"
  - "end_time"
  - "NAS_PDU"

identifier_conversion:
  ip_src : ip_address
  ip_dst : ip_address
  ipv4   : ip_address
  nfInstanceId: nfInstanceId
  ausfInstanceId: nfInstanceId
  jwt.sub: nfInstanceId
  node_id_fqdn: ipEndPoint
  ipEndPoints: ipEndPoints
  apiPrefix: apiPrefix
  imsi: imsi
  Timestamp : ts
  jwt.iat : unix_ts
  jwt.exp : unix_ts
  pLMNIdentity : plmn_id
  NRCellIdentity : nrcell_id
  msg_auth_code : auth_code
  teid : teid
  seq_number : seq_number
  amfId : amf_id
  seid : seid

input_tensor_dimension: 1024

window_size: 1000
window_shift: 500

split_ratio: 0.80
batch_size: 32

training_params :
  learning_rate: 0.005
  weight_decay: 0.001
  num_epochs: 100
  early_stopping_patience: 15
  log_interval: 10
