# Parameters for dissection pipeline

# Input directory
initial_raw_file: "data/initial_raw/benign.pcap"

evil_ip : 10.100.200.66

# Banned features list
banned_features:
  - "versions"
  - "scheme"
  - "ipEndPoints"
  - "apiPrefix"
  - "subscribedUeAmbr"
  - "dnnInfos"
  - "jwt.alg"
  - "jwt.typ"

identifier_list:
  - ip_src
  - ip_dst
  - Timestamp
  - jwt.iat
  - jwt.exp

input_tensor_dimension: 1024

window_size: 1000
window_shift: 500

split_ratio: 0.80
batch_size: 32